### ISSUE TITLE
Tipos de arquivo

### ISSUE THREAD

**Issue by gmelodie** [BrunoGomesCoelho/Organiza-oDeArquivosT1#10]
Preciso saber exatamente como são os arquivos:

- Campos de tamanho fixo (sem indicadores de tamanho e sem delimitadores)
- Campos de tamanho variável (com indicadores de tamanho e sem delimitadores)
### Registros (sempre de tamanho variável):
   - Com indicadores de tamanho.
   - Com delimitadores
   - Com número fixo de campos (sem delimitadores e sem indicadores de tamanho)

É certo isso?

**Comment by gmelodie** [comment]
Ok, li o PDF e vi a implementação do martchellop:
### Delimitadores:
- **#** -> fim do registro
- **;** -> fim do campo [NÃO USAREMOS]
### Campos:
- Tamanho variável (com indicador de tamanho e sem delimitador)
- Tamanho fixo (sem indicador de tamanho e sem delimitador)

### Registros (sempre tamanho variável):
- Com indicadores de tamanho.
- Com delimitadores
- Com número fixo de campos (contamos o número de campos até agora para saber quando acaba o registro)

### Problemas
1. Precisamos ainda escolher o tamanho dos campos de tamanho fixo. Acredito que o nenhum dos campos deve passar de 19 caracteres (20 se incluirmos o \0 e 21 incluindo delimitador). Dessa forma, para dar um sossego a mais, proponho que usemos 30 caracteres reservados para esses campos.

2. O campo "ticket" pode passar de 9 caracteres, eventualmente, visto que se chega facilmente a 9 no exemplo dado. Se a professora resolver rodar outros testes é capaz de estourarmos o intieiro, sugiro que coloquemos todos os campos como strings para evitar problemas com bounds de tipos primitivos.


*Obs.: Precisamos escrever no PDF a decisão de usar 30 bytes para os campos de tamanho fixo.*

**Comment by BrunoGomesCoelho** [comment]
Os campos de tamanho fixo não tem obrigatoriamente todos que ter o mesmo tamanho, só têm que ser fixo entre sí. 

Acho que para aqueles que nem o número do documento que tem uma formatação bem definida, poderia usarmos o tamanho dele (ou +1 para o \0), afinal não faz muito sentido usar mais pois só gastariamos memória a toa.

Falando em \0, facilitaria muito a vida incluir o \0 como parte de todas as strings para na hora de ler não ter que adicionar ele para depois imprimir.

Sou a favor de tratar ticket como string também

**Comment by gmelodie** [comment]
Então, acho que usar o tamanho fixo constante para todos os campos é uma escolha legal justamente porque evitaríamos de usar muitas cláusulas IF/ELSE. Eu particularmente procuro deixar o caso sempre geral, ainda que gaste um pouco mais de memória.

**Comment by BrunoGomesCoelho** [comment]
Mas os campos seguem sempre a mesma ordem, não entendi porque precisaria de IF/ELSE...

**Comment by gmelodie** [comment]
Pq cada campo fixo teria seu próprio tamanho, aí teria um if para cada
campo fixo indicando seu respectivo tamanho
Em 7 de mai de 2017 14:23, "Bruno Gomes Coelho" <notifications@github.com>
escreveu:

**Comment by BrunoGomesCoelho** [comment]
Ainda não entendi mas talvez seja uma questão de funções diferentes.
Nas minhas, tenho que ler todos os campos de qualquer maneira então só faço
fread(destino, SIZE_CAMPO, 1, fp).
Preciso ler todos então preciso de vários fread para guardar em lugares diferentes, então mudar o SIZE_CAMPO por fread é trivial.

Você pode dar um exemplo desses ifs?

**Comment by gmelodie** [comment]
Ah sim. No meu caso eu preciso fazer: 
``` 
if (field == DOCUMENT) 
           fwrite(size(15)) 
```
 se o campo for documento. Agora, se o campo for outro, por exemplo ticket, preciso escrever outro tamanho. Seria mais fácil fazer:

``` 
if (field == DOCUMENT || field == TIKET || ...) 
           fwrite(SIZE_FIXED) 
```
No primeiro exemplo, cada campo deveria ter um *if statement* diferente. No segundo, por outro lado, trataria tudo em um caso apenas.

**Comment by BrunoGomesCoelho** [comment]
Ah, entendi. Então por mim tudo bem, você pode preencher com \0? Facilitaria muito na impressão
