### ISSUE TITLE
Encoding dos arquivos de saída

### ISSUE THREAD

**Issue by gmelodie** [BrunoGomesCoelho/Organiza-oDeArquivosT1#11]
Os arquivos gerados na saída do programa parecem aprensentar erros quanto ao encoding quando há, por exemplo, acentos e outros caracteres especiais. Não faço ideia de como resolver esse problema já que a ciferri parece tirar ponto por saídas mal formatadas.

**Comment by BrunoGomesCoelho** [comment]
Acho que talvez isso daqui resolva nossos problemas: http://linguagemc.com.br/localizacao-de-programas-com-locale-h/

**Comment by gmelodie** [comment]
Então, tentei aqui e parece funcionar. O problema é que precisamos mudar o encoding na hora de ler os arquivos (fread). Não tenho certeza de que isso é o problema, mas é meu melhor chute aqui, outro problema pode ser que eu não tenha entendido direito como funciona o setlocale e tenha feito algo errado, mas acredito que não.

**Comment by BrunoGomesCoelho** [comment]
> Então, tentei aqui e parece funcionar.

Boooooooa, mito.

Hmm, saquei depois a gente mete caso de teste pra cacete
