### ISSUE TITLE
Escolha do arquivo

### ISSUE THREAD

**Issue by gmelodie** [BrunoGomesCoelho/Organiza-oDeArquivosT1#4]
Poderiamos fazer uma funcao que pede ao usuario o tipo de organizacão do arquivo (registro, campos) e retorna à main um número correspondente. Vamos modularizar ao máximo e evitar deixar o código com muitos IF/ELSE ou SWITCH/CASE statements

**Comment by BrunoGomesCoelho** [comment]
Então, o problema é que ainda temos que chamar a função correspondente (printRegistroIndicadorDeTamanho por exemplo), e para isso vamos ter que fazer um if/else if/else dos números retornados :/
