### ISSUE TITLE
Indicador de tamanho

### ISSUE THREAD

**Issue by ghost** [BrunoGomesCoelho/Organiza-oDeArquivosT1#6]
Estou supondo que tanto o registro quanto int tem indicador de tamanho, o do registro no inicio e o do int antes do número.

Também suponho que as strings vão ser salvas com o \0 nelas

**Comment by BrunoGomesCoelho** [comment]
Não entendi o negócio do int

**Comment by ghost** [comment]
o indicador de tamanho diz a quantidade de bytes que o campo ocupa. Então no int é pra ter | 4 | n

**Comment by BrunoGomesCoelho** [comment]
Ahhh saquei

**Comment by gmelodie** [comment]
É para fazer com indicador de tamanho em qualquer caso. Ela falou que não é para otimizar de forma alguma, só faça.
