### ISSUE TITLE
Podemos considerar que sabemos a quantidade de registros?

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [BrunoGomesCoelho/Organiza-oDeArquivosT1#8]
A dúvida pode parecer meio idiota, mas para os campos por exemplo não podemos fazer um
    for(i=0; i<qtdCampos; i++)
em todos os casos (só para número fixo de campos), pois estariamos considerando uma quantidade fixa de campos.

Uma vez que estamos usando registros com tamanho variável e indicadores de tamanho, a mesma lógica não se aplicaria?

**Comment by gmelodie** [comment]
Vai haver uma variável indicando a quantidade de registros e outra indicando quantidade de campos por registro que será retornada por referência pelas funções de leitura do arquivo.

**Comment by BrunoGomesCoelho** [comment]
Então, o meu problema é com essa variável e usar ele num for, porque é exatamente assim que implementariamos se fosse quantidade fixa de registro (que não é uma das opções de implementação) e ela deixou claro que:

"Não é permitido misturar os métodos para organizar em registros. Por exemplo, não é permitido misturar o método número fixo de campos com o método delimitadores entre registros. Ou seja, cada método deve ser implementado de forma separada, conforme solicitado."
